SELECT YEAR,ETHNICITY,AGE_COHORT,SUM(POPULATION) as POPULATION from  CDC_85_PLUS_POPULATION  WHERE ESTIMATE_MONTH=7 AND SERIES_VINTAGE=2019 group by YEAR,ETHNICITY,AGE_COHORT order by YEAR,ETHNICITY,AGE_COHORT

SELECT YEAR,ETHNICITY,AGE_COHORT,(POPULATION) as POPULATION from  CDC_85_PLUS_POPULATION  WHERE ESTIMATE_MONTH=7 AND SERIES_VINTAGE=2019

SELECT *  from  MIT_MORTALITY_BY_BIRTH_YEAR_DATA WHERE OBS_BY_BIRTH_YEAR>0 AND CANCER_TYPE=  'Cardiovascular Disease'--'Alzheimers Disease' 
AND YEAR_OF_BIRTH_COHORT_TYPE=10 AND ETHNICITY='EAM' 
order by AGE_AT_DEATH 


